apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/publicEndpoints: '[{"addresses":["34.67.89.35"],"port":23306,"protocol":"TCP","serviceName":"mysql-staging:mysql-lb","allNodes":false}]'
  creationTimestamp: "2019-12-20T15:35:50Z"
  generation: 5
  labels:
    app: mysql
    chart: mysql-1.3.1
    heritage: Tiller
    io.cattle.field/appId: mysql
    release: mysql
  name: mysql
  namespace: mysql-staging
  resourceVersion: "41240106"
  selfLink: /apis/extensions/v1beta1/namespaces/mysql-staging/deployments/mysql
  uid: 66be67bc-233e-11ea-9852-42010a8000ff
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-02-14T08:19:01Z"
        field.cattle.io/ports: '[[{"containerPort":3306,"dnsName":"mysql-","name":"mysql","protocol":"TCP","sourcePort":0}],[{"containerPort":9104,"dnsName":"mysql-","name":"metrics","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance_type
                operator: In
                values:
                - persistent
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: idcreator
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql
              optional: false
        image: ranchercharts/mysql:5.7.14
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mysql/conf.d/mysql.cnf
          name: configurations
          subPath: mysql.cnf
        - mountPath: /var/lib/mysql
          name: data
      - command:
        - sh
        - -c
        - DATA_SOURCE_NAME="root:$MYSQL_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql
              optional: false
        image: ranchercharts/prom-mysqld-exporter:v0.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: metrics
        ports:
        - containerPort: 9104
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - rm
        - -fr
        - /var/lib/mysql/lost+found
        image: ranchercharts/busybox:1.29.3
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      nodeSelector:
        instance_type: persistent
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-configuration
        name: configurations
      - name: data
        persistentVolumeClaim:
          claimName: mysql
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-09T06:51:52Z"
    lastUpdateTime: "2020-01-09T06:51:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-20T15:35:50Z"
    lastUpdateTime: "2020-02-14T08:19:58Z"
    message: ReplicaSet "mysql-6759df8978" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
