apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-wgcfv
  creationTimestamp: "2020-02-04T13:16:12Z"
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-mysql-staging-mysql-client
  name: mysql-client
  namespace: mysql-staging
  resourceVersion: "38373961"
  selfLink: /apis/extensions/v1beta1/namespaces/mysql-staging/deployments/mysql-client
  uid: 83e57d45-4750-11ea-9d8a-42010a800055
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-mysql-staging-mysql-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-02-04T13:16:11Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-mysql-staging-mysql-client
    spec:
      containers:
      - args:
        - -c
        - cat
        command:
        - /bin/sh
        image: arey/mysql-client
        imagePullPolicy: Always
        name: mysql-client
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-04T13:16:12Z"
    lastUpdateTime: "2020-02-04T13:16:14Z"
    message: ReplicaSet "mysql-client-67fc7cff76" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-08T11:25:11Z"
    lastUpdateTime: "2020-02-08T11:25:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
