apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-19T20:08:17Z"
  labels:
    app: redis
    chart: redis-9.0.2
    heritage: Tiller
    io.cattle.field/appId: redis-cache
    release: redis-cache
  name: redis-cache-headless
  namespace: redis-staging
  resourceVersion: "478343"
  selfLink: /api/v1/namespaces/redis-staging/services/redis-cache-headless
  uid: 5384cdf5-0b08-11ea-b777-42010a80017f
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-cache
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
