apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-19T20:09:39Z"
  labels:
    app: redis
    chart: redis-9.0.2
    heritage: Tiller
    io.cattle.field/appId: redis-frontend
    release: redis-frontend
  name: redis-frontend-master
  namespace: redis-staging
  resourceVersion: "478769"
  selfLink: /api/v1/namespaces/redis-staging/services/redis-frontend-master
  uid: 843fce81-0b08-11ea-b777-42010a80017f
spec:
  clusterIP: 10.28.4.39
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-frontend
    role: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
