apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2019-12-20T15:35:50Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mysql
    chart: mysql-1.3.1
    heritage: Tiller
    io.cattle.field/appId: mysql
    release: mysql
  name: mysql
  namespace: mysql-staging
  resourceVersion: "14031172"
  selfLink: /api/v1/namespaces/mysql-staging/persistentvolumeclaims/mysql
  uid: 66a59809-233e-11ea-9852-42010a8000ff
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ssd
  volumeMode: Filesystem
  volumeName: pvc-66a59809-233e-11ea-9852-42010a8000ff
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
