apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:mysql-staging:mysql-client"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-02-04T13:16:12Z"
  labels:
    cattle.io/creator: norman
  name: mysql-client
  namespace: mysql-staging
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: mysql-client
    uid: 83e57d45-4750-11ea-9d8a-42010a800055
  resourceVersion: "36460766"
  selfLink: /api/v1/namespaces/mysql-staging/services/mysql-client
  uid: 83e7e02f-4750-11ea-9d8a-42010a800055
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-mysql-staging-mysql-client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
