apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-wgcfv
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/publicEndpoints: '[{"addresses":["34.67.89.35"],"port":23306,"protocol":"TCP","serviceName":"mysql-staging:mysql-lb","allNodes":false}]'
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: "2020-01-03T11:06:01Z"
  labels:
    cattle.io/creator: norman
  name: mysql-lb
  namespace: mysql-staging
  resourceVersion: "20802356"
  selfLink: /api/v1/namespaces/mysql-staging/services/mysql-lb
  uid: 06c3801c-2e19-11ea-9852-42010a8000ff
spec:
  clusterIP: 10.28.2.47
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    nodePort: 31484
    port: 23306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.67.89.35
