apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-20T15:35:50Z"
  labels:
    app: mysql
    chart: mysql-1.3.1
    heritage: Tiller
    io.cattle.field/appId: mysql
    release: mysql
  name: mysql
  namespace: mysql-staging
  resourceVersion: "14031138"
  selfLink: /api/v1/namespaces/mysql-staging/services/mysql
  uid: 66ad3a6f-233e-11ea-9852-42010a8000ff
spec:
  clusterIP: 10.28.2.127
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: metrics
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
