apiVersion: v1
data:
  run.sh: |-
    @test "Testing MySQL Connection" {
      mysql --host=mysql --port=3306 -u root -phJkaNkoIhZmHJSuiaysg
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-20T15:35:50Z"
  labels:
    app: mysql
    chart: mysql-1.3.1
    heritage: Tiller
    io.cattle.field/appId: mysql
    release: mysql
  name: mysql-test
  namespace: mysql-staging
  resourceVersion: "14031133"
  selfLink: /api/v1/namespaces/mysql-staging/configmaps/mysql-test
  uid: 669d73a0-233e-11ea-9852-42010a8000ff
