apiVersion: v1
data:
  LDAP_DOMAIN: odms.dev
  LDAP_ORGANISATION: ODMS
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-24T18:33:54Z"
  labels:
    cattle.io/creator: norman
  name: ldap-config
  namespace: staging
  resourceVersion: "7170865"
  selfLink: /api/v1/namespaces/staging/configmaps/ldap-config
  uid: a42a59aa-19e0-4f7b-b49a-f832954cd937
