apiVersion: v1
data:
  CONTEXT_DIR: /workspace/mis_mdm
  LIQUIBASE_CHANGELOG: mis_mdm.yaml
  LIQUIBASE_DATABASE: odms
  LIQUIBASE_DEFAULT_SCHEMA_NAME: public
  LIQUIBASE_HOST: dbms
  LIQUIBASE_LOGLEVEL: finest
  LIQUIBASE_PASSWORD: postgres
  LIQUIBASE_USERNAME: postgres
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-31T10:48:34Z"
  labels:
    cattle.io/creator: norman
  name: liquibase-mis-mdm
  namespace: staging
  resourceVersion: "8314791"
  selfLink: /api/v1/namespaces/staging/configmaps/liquibase-mis-mdm
  uid: 6d5eda14-6057-4d1b-8ed1-eab4901ccaa6
