apiVersion: v1
data:
  CONTEXT_DIR: /workspace/odms_oltp
  LIQUIBASE_CHANGELOG: odms_oltp.yaml
  LIQUIBASE_DATABASE: odms
  LIQUIBASE_DEFAULT_SCHEMA_NAME: public
  LIQUIBASE_HOST: postgres
  LIQUIBASE_LOGLEVEL: finest
  LIQUIBASE_PASSWORD: postgres
  LIQUIBASE_USERNAME: postgres
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-31T10:48:54Z"
  labels:
    cattle.io/creator: norman
  name: liquibase-odms-oltp
  namespace: staging
  resourceVersion: "8314841"
  selfLink: /api/v1/namespaces/staging/configmaps/liquibase-odms-oltp
  uid: 3e86c02c-beb3-4ce1-bb2c-4d18108b1014
