apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-31T12:01:21Z"
  labels:
    app: rabbitmq
    chart: rabbitmq-6.16.0
    heritage: Tiller
    io.cattle.field/appId: rabbitmq
    release: rabbitmq
  name: rabbitmq-headless
  namespace: rabbitmq
  resourceVersion: "19355857"
  selfLink: /api/v1/namespaces/rabbitmq/services/rabbitmq-headless
  uid: 4293e308-2bc5-11ea-9852-42010a8000ff
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: dist
  - name: stats
    port: 15672
    protocol: TCP
    targetPort: stats
  selector:
    app: rabbitmq
    release: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
