apiVersion: v1
kind: Pod
metadata:
  name: "jenkins-slave-docker"
  labels:
    name: "jenkins-slave-docker"
    namespace: jenkins
spec:
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: File
  containers:
  - name: "jnlp"
    image: "dawnbreather/jnlp-slave:3.27-1"
    workingDir: /home/jenkins
    env:
    - name: "JENKINS_URL"
      value: "http://jenkins.jenkins.svc.cluster.local:8080"
    - name: JENKINS_TUNNEL
      value: jenkins-agent:50000
    args: ["123", "123"]
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    #securityContext:
    #  runAsUser: 1000
    #  runAsGroup: 1000
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "200m"