apiVersion: v1
data:
  rabbitmq-erlang-cookie: MmJCQ0JYc0l5cDRVSHhPVnVSenBLb2dvc1doTXd3WjI=
  rabbitmq-password: QVJIblBqeEM0VA==
kind: Secret
metadata:
  creationTimestamp: "2019-12-31T12:01:21Z"
  labels:
    app: rabbitmq
    chart: rabbitmq-6.16.0
    heritage: Tiller
    io.cattle.field/appId: rabbitmq
    release: rabbitmq
  name: rabbitmq
  namespace: rabbitmq
  resourceVersion: "19358922"
  selfLink: /api/v1/namespaces/rabbitmq/secrets/rabbitmq
  uid: 42665caf-2bc5-11ea-9852-42010a8000ff
type: Opaque
