apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: user-wgcfv
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-cache-staging-nfs-provisioner
  creationTimestamp: "2019-12-01T23:22:53Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: cache-staging
  namespace: staging
  resourceVersion: "4721178"
  selfLink: /api/v1/namespaces/staging/persistentvolumeclaims/cache-staging
  uid: 8000fa55-1491-11ea-8d66-42010a8000a1
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 1932735283200m
  storageClassName: nfs-cache-staging
  volumeMode: Filesystem
  volumeName: pvc-8000fa55-1491-11ea-8d66-42010a8000a1
status:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 1932735283200m
  phase: Bound
