apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: user-wgcfv
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-nfs-provisioner
  creationTimestamp: "2019-11-27T01:44:33Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: media-staging
  namespace: staging
  resourceVersion: "2858604"
  selfLink: /api/v1/namespaces/staging/persistentvolumeclaims/media-staging
  uid: 76432da6-10b7-11ea-8d66-42010a8000a1
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 19968Mi
  storageClassName: nfs-staging
  volumeMode: Filesystem
  volumeName: pvc-76432da6-10b7-11ea-8d66-42010a8000a1
status:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 19968Mi
  phase: Bound
