apiVersion: v1
data:
  mysql-password: aEprYU5rb0loWm1ISlN1aWF5c2c=
  mysql-root-password: aEprYU5rb0loWm1ISlN1aWF5c2c=
kind: Secret
metadata:
  creationTimestamp: "2019-12-20T15:35:50Z"
  labels:
    app: mysql
    chart: mysql-1.3.1
    heritage: Tiller
    io.cattle.field/appId: mysql
    release: mysql
  name: mysql
  namespace: mysql-staging
  resourceVersion: "14031130"
  selfLink: /api/v1/namespaces/mysql-staging/secrets/mysql
  uid: 668d1b51-233e-11ea-9852-42010a8000ff
type: Opaque
