apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-12-01T23:21:04Z"
  generation: 2
  labels:
    app: nfs-provisioner
    chart: nfs-provisioner-0.3.0
    heritage: Tiller
    io.cattle.field/appId: nfs-cache-staging
    release: nfs-cache-staging
  name: nfs-cache-staging-nfs-provisioner
  namespace: nfs-staging
  resourceVersion: "37759920"
  selfLink: /apis/apps/v1/namespaces/nfs-staging/statefulsets/nfs-cache-staging-nfs-provisioner
  uid: 3f16e4b4-1491-11ea-8d66-42010a8000a1
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-provisioner
      release: nfs-cache-staging
  serviceName: nfs-cache-staging-nfs-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-provisioner
        chart: nfs-provisioner-0.3.0
        heritage: Tiller
        release: nfs-cache-staging
    spec:
      containers:
      - args:
        - -provisioner=cluster.local/nfs-cache-staging-nfs-provisioner
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_NAME
          value: nfs-cache-staging-nfs-provisioner
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ranchercharts/kubernetes_incubator-nfs-provisioner:v2.2.1-k8s1.12
        imagePullPolicy: IfNotPresent
        name: nfs-provisioner
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 111
          name: rpcbind-tcp
          protocol: TCP
        - containerPort: 111
          name: rpcbind-udp
          protocol: UDP
        resources: {}
        securityContext:
          capabilities:
            add:
            - DAC_READ_SEARCH
            - SYS_RESOURCE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        instance_type: persistent
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-cache-staging-nfs-provisioner
      serviceAccountName: nfs-cache-staging-nfs-provisioner
      terminationGracePeriodSeconds: 100
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: ssd
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: nfs-cache-staging-nfs-provisioner-6dfc5c55cd
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updateRevision: nfs-cache-staging-nfs-provisioner-6dfc5c55cd
  updatedReplicas: 1
