apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdG9yeS5lcGFtLmNvbTo2MTM1Ijp7ImF1dGgiOiJRWFYwYjE5RlVFMHRRMGhTVkY5S1pXNXJhVzV6TFVkSlZGOUpiblJsWjNKaGRHbHZia0JsY0dGdExtTnZiVHBHVjFnMk9XRnVaSEpDUkRkS2VrRldVakpUTkZKMFRuQjIiLCJwYXNzd29yZCI6IkZXWDY5YW5kckJEN0p6QVZSMlM0UnROcHYiLCJ1c2VybmFtZSI6IkF1dG9fRVBNLUNIUlRfSmVua2lucy1HSVRfSW50ZWdyYXRpb25AZXBhbS5jb20ifX19
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
    field.cattle.io/projectId: c-9mxfh:p-vvt7s
    lifecycle.cattle.io/create.secretsController_c-9mxfh: "true"
    secret.user.cattle.io/secret: "true"
  creationTimestamp: "2020-05-01T16:15:20Z"
  name: epam-artifactory
  namespace: staging
  resourceVersion: "4622038"
  selfLink: /api/v1/namespaces/staging/secrets/epam-artifactory
  uid: 94c079b4-8af0-492e-a36f-2cd553ad3d78
type: kubernetes.io/dockerconfigjson
