apiVersion: v1
data:
  POSTGRES_DB: b2Rtcw==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-31T10:51:23Z"
  labels:
    cattle.io/creator: norman
  name: postgres
  namespace: staging
  resourceVersion: "8315239"
  selfLink: /api/v1/namespaces/staging/secrets/postgres
  uid: f2d35f9e-1eb5-4fc1-ae18-d4aa81e264fc
type: Opaque
