apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2019-12-31T12:01:21Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: rabbitmq
    release: rabbitmq
  name: data-rabbitmq-0
  namespace: rabbitmq
  resourceVersion: "19355904"
  selfLink: /api/v1/namespaces/rabbitmq/persistentvolumeclaims/data-rabbitmq-0
  uid: 42a4852d-2bc5-11ea-9852-42010a8000ff
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-42a4852d-2bc5-11ea-9852-42010a8000ff
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
