apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: "2020-05-24T18:19:35Z"
  labels:
    cattle.io/creator: norman
  name: backend
  namespace: staging
  resourceVersion: "7168682"
  selfLink: /api/v1/namespaces/staging/services/backend
  uid: d2e75d7c-90ea-4e0f-bd21-9102b79addfb
spec:
  clusterIP: None
  ports:
  - name: tcp-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    stack: odms
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
