apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:staging:pgadmin"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-05-31T10:45:11Z"
  labels:
    cattle.io/creator: norman
  name: pgadmin
  namespace: staging
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: pgadmin
    uid: 05be4139-2594-4d46-9029-f1f4284cd2a3
  resourceVersion: "8314182"
  selfLink: /api/v1/namespaces/staging/services/pgadmin
  uid: f442ebdc-29bf-4e4e-9ef5-a0d0e267f23b
spec:
  clusterIP: 10.43.40.172
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-staging-pgadmin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
