apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.6.217.156","10.6.222.212","10.6.223.128","10.6.223.76"],"port":80,"protocol":"HTTP","serviceName":"staging:backend","ingressName":"staging:odms","hostname":"odms.vok.today","path":"/api","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"stack":"odms","tier":"backend"},"name":"backend","namespace":"staging"},"spec":{"selector":{"matchLabels":{"stack":"odms","tier":"backend"}},"template":{"metadata":{"labels":{"stack":"odms","tier":"backend"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"backend-envvar"}},{"configMapRef":{"name":"backend-envvar"}}],"image":"artifactory.epam.com:6135/odms-app:80","imagePullPolicy":"Always","name":"backend","ports":[{"containerPort":8082,"name":"http","protocol":"TCP"}]}],"imagePullSecrets":[{"name":"epam-artifactory"}]}}}}'
  creationTimestamp: "2020-05-24T18:18:47Z"
  generation: 14
  labels:
    stack: odms
    tier: backend
  name: backend
  namespace: staging
  resourceVersion: "8316946"
  selfLink: /apis/apps/v1/namespaces/staging/deployments/backend
  uid: 81bdef3b-9ea9-4ab3-8cda-95fd2f5dabdc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      stack: odms
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-31T10:50:02Z"
        field.cattle.io/ports: '[[{"containerPort":8082,"dnsName":"backend","hostPort":0,"kind":"ClusterIP","name":"http","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        stack: odms
        tier: backend
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: backend
            optional: false
        - configMapRef:
            name: backend
            optional: false
        image: artifactory.epam.com:6135/odms-app:80
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: epam-artifactory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-05-31T08:57:32Z"
    lastUpdateTime: "2020-05-31T08:57:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-05-31T11:00:06Z"
    lastUpdateTime: "2020-05-31T11:00:06Z"
    message: ReplicaSet "backend-74c94d9986" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 14
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
