apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.6.217.156","10.6.222.212","10.6.223.128","10.6.223.76"],"port":80,"protocol":"HTTP","serviceName":"staging:frontend","ingressName":"staging:odms","hostname":"odms.vok.today","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"frontend","namespace":"staging"},"spec":{"selector":{"matchLabels":{"stack":"odms","tier":"frontend"}},"template":{"metadata":{"labels":{"stack":"odms","tier":"frontend"}},"spec":{"containers":[{"image":"artifactory.epam.com:6135/odms-app-frontend:feature-cicd-5","imagePullPolicy":"IfNotPresent","name":"frontend","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}]}],"imagePullSecrets":[{"name":"epam-artifactory"}]}}}}'
  creationTimestamp: "2020-05-24T18:21:52Z"
  generation: 4
  name: frontend
  namespace: staging
  resourceVersion: "8315696"
  selfLink: /apis/apps/v1/namespaces/staging/deployments/frontend
  uid: 51391ca4-c5e8-4cbe-aa30-a1192e506ca0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      stack: odms
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-31T10:54:00Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"frontend","hostPort":0,"kind":"ClusterIP","name":"http","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        stack: odms
        tier: frontend
    spec:
      containers:
      - image: artifactory.epam.com:6135/odms-app-frontend:feature-cicd-5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: frontend
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: epam-artifactory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-30T15:28:56Z"
    lastUpdateTime: "2020-05-30T15:28:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-24T18:21:52Z"
    lastUpdateTime: "2020-05-31T10:54:17Z"
    message: ReplicaSet "frontend-59f4467d9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
