apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    field.cattle.io/creatorId: user-7p9hq
    field.cattle.io/publicEndpoints: '[{"addresses":["10.6.217.156","10.6.222.212","10.6.223.128","10.6.223.76"],"port":80,"protocol":"HTTP","serviceName":"staging:pgadmin","ingressName":"staging:pgadmin","hostname":"pgadmin-odms.vok.today","allNodes":false}]'
  creationTimestamp: "2020-05-31T10:45:11Z"
  generation: 13
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-staging-pgadmin
  name: pgadmin
  namespace: staging
  resourceVersion: "8318330"
  selfLink: /apis/apps/v1/namespaces/staging/deployments/pgadmin
  uid: 05be4139-2594-4d46-9029-f1f4284cd2a3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-staging-pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-31T11:06:33Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"pgadmin","hostPort":0,"kind":"ClusterIP","name":"http","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-staging-pgadmin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pgadmin
            optional: false
        image: dpage/pgadmin4:4.20
        imagePullPolicy: IfNotPresent
        name: pgadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-31T11:06:55Z"
    lastUpdateTime: "2020-05-31T11:06:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-31T10:45:11Z"
    lastUpdateTime: "2020-05-31T11:06:55Z"
    message: ReplicaSet "pgadmin-899cd746c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
