apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:staging:idc"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2019-11-26T22:03:45Z"
  labels:
    cattle.io/creator: norman
  name: idc
  namespace: staging
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: idc
    uid: 4cf740aa-1098-11ea-8d66-42010a8000a1
  resourceVersion: "2809290"
  selfLink: /api/v1/namespaces/staging/services/idc
  uid: 9df6d734-1098-11ea-8d66-42010a8000a1
spec:
  clusterIP: 10.28.2.206
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: deployment-staging-idc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
