apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["daemonset:staging:static-content-each-node"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2019-11-26T21:02:30Z"
  labels:
    cattle.io/creator: norman
  name: static-content-each-node
  namespace: staging
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: static-content-each-node
    uid: 0f0917aa-1090-11ea-8d66-42010a8000a1
  resourceVersion: "2782861"
  selfLink: /api/v1/namespaces/staging/services/static-content-each-node
  uid: 0f0ac45d-1090-11ea-8d66-42010a8000a1
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-staging-static-content-each-node
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
