package resources

import "time"

type AutoGenerated struct {
	Type  string `json:"type"`
	Links struct {
		Self string `json:"self"`
	} `json:"links"`
	CreateTypes struct {
		ConfigMap string `json:"configMap"`
	} `json:"createTypes"`
	Actions struct {
	} `json:"actions"`
	Pagination struct {
		Limit int `json:"limit"`
		Total int `json:"total"`
	} `json:"pagination"`
	Sort struct {
		Order   string `json:"order"`
		Reverse string `json:"reverse"`
		Links   struct {
			UUID string `json:"uuid"`
		} `json:"links"`
	} `json:"sort"`
	Filters struct {
		Created     interface{} `json:"created"`
		CreatorID   interface{} `json:"creatorId"`
		Name        interface{} `json:"name"`
		NamespaceID interface{} `json:"namespaceId"`
		ProjectID   interface{} `json:"projectId"`
		Removed     interface{} `json:"removed"`
		UUID        interface{} `json:"uuid"`
	} `json:"filters"`
	ResourceType string `json:"resourceType"`
	Data         []struct {
		Annotations struct {
		} `json:"annotations,omitempty"`
		BaseType  string    `json:"baseType"`
		Created   time.Time `json:"created"`
		CreatedTS int64     `json:"createdTS"`
		CreatorID string    `json:"creatorId"`
		Data      struct {
			Some string `json:"some"`
		} `json:"data,omitempty"`
		ID     string `json:"id"`
		Labels struct {
			CattleIoCreator string `json:"cattle.io/creator"`
		} `json:"labels,omitempty"`
		Links struct {
			Remove string `json:"remove"`
			Self   string `json:"self"`
			Update string `json:"update"`
			Yaml   string `json:"yaml"`
		} `json:"links"`
		Name        string `json:"name"`
		NamespaceID string `json:"namespaceId"`
		ProjectID   string `json:"projectId"`
		Type        string `json:"type"`
		UUID        string `json:"uuid"`
		Data        struct {
			NginxConf string `json:"nginx.conf"`
		} `json:"data,omitempty"`
		Labels struct {
			App                string `json:"app"`
			IoCattleFieldAppID string `json:"io.cattle.field/appId"`
			Release            string `json:"release"`
		} `json:"labels,omitempty"`
		Data struct {
			Release string `json:"release"`
		} `json:"data,omitempty"`
		Labels struct {
			MODIFIEDAT string `json:"MODIFIED_AT"`
			NAME       string `json:"NAME"`
			OWNER      string `json:"OWNER"`
			STATUS     string `json:"STATUS"`
			VERSION    string `json:"VERSION"`
		} `json:"labels,omitempty"`
		Data struct {
			Release string `json:"release"`
		} `json:"data,omitempty"`
		Labels struct {
			MODIFIEDAT string `json:"MODIFIED_AT"`
			NAME       string `json:"NAME"`
			OWNER      string `json:"OWNER"`
			STATUS     string `json:"STATUS"`
			VERSION    string `json:"VERSION"`
		} `json:"labels,omitempty"`
		Data struct {
			Release string `json:"release"`
		} `json:"data,omitempty"`
		Labels struct {
			MODIFIEDAT string `json:"MODIFIED_AT"`
			NAME       string `json:"NAME"`
			OWNER      string `json:"OWNER"`
			STATUS     string `json:"STATUS"`
			VERSION    string `json:"VERSION"`
		} `json:"labels,omitempty"`
		Data struct {
			MasterConf  string `json:"master.conf"`
			RedisConf   string `json:"redis.conf"`
			ReplicaConf string `json:"replica.conf"`
		} `json:"data,omitempty"`
		Labels struct {
			App                string `json:"app"`
			Chart              string `json:"chart"`
			Heritage           string `json:"heritage"`
			IoCattleFieldAppID string `json:"io.cattle.field/appId"`
			Release            string `json:"release"`
		} `json:"labels,omitempty"`
		Data struct {
			PingLivenessLocalSh           string `json:"ping_liveness_local.sh"`
			PingLivenessLocalAndMasterSh  string `json:"ping_liveness_local_and_master.sh"`
			PingLivenessMasterSh          string `json:"ping_liveness_master.sh"`
			PingReadinessLocalSh          string `json:"ping_readiness_local.sh"`
			PingReadinessLocalAndMasterSh string `json:"ping_readiness_local_and_master.sh"`
			PingReadinessMasterSh         string `json:"ping_readiness_master.sh"`
		} `json:"data,omitempty"`
		Labels struct {
			App                string `json:"app"`
			Chart              string `json:"chart"`
			Heritage           string `json:"heritage"`
			IoCattleFieldAppID string `json:"io.cattle.field/appId"`
			Release            string `json:"release"`
		} `json:"labels,omitempty"`
		Data struct {
			Release string `json:"release"`
		} `json:"data,omitempty"`
		Labels struct {
			MODIFIEDAT string `json:"MODIFIED_AT"`
			NAME       string `json:"NAME"`
			OWNER      string `json:"OWNER"`
			STATUS     string `json:"STATUS"`
			VERSION    string `json:"VERSION"`
		} `json:"labels,omitempty"`
	} `json:"data"`
}