apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-24T18:02:01Z"
  labels:
    cattle.io/creator: norman
  name: liquibase-epmr
  namespace: staging
  resourceVersion: "7166350"
  selfLink: /apis/batch/v1/namespaces/staging/jobs/liquibase-epmr
  uid: 540d77a8-c29c-4ed1-b073-1b150e2403a9
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 540d77a8-c29c-4ed1-b073-1b150e2403a9
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-24T18:02:00Z"
      creationTimestamp: null
      labels:
        controller-uid: 540d77a8-c29c-4ed1-b073-1b150e2403a9
        job-name: liquibase-epmr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: liquibase-epmr-envvar
            optional: false
        image: dawnbreather/tmp:liquibase-odms-demographics-mdm
        imagePullPolicy: IfNotPresent
        name: liquibase-epmr
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2020-05-24T18:05:06Z"
  conditions:
  - lastProbeTime: "2020-05-24T18:05:06Z"
    lastTransitionTime: "2020-05-24T18:05:06Z"
    status: "True"
    type: Complete
  failed: 1
  startTime: "2020-05-24T18:02:01Z"
  succeeded: 1
