apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    field.cattle.io/creatorId: user-7p9hq
  creationTimestamp: "2020-05-24T18:01:04Z"
  labels:
    cattle.io/creator: norman
  name: liquibase-odms-oltp
  namespace: staging
  resourceVersion: "7166385"
  selfLink: /apis/batch/v1/namespaces/staging/jobs/liquibase-odms-oltp
  uid: fcbf26bb-9e19-4541-9560-a4d56c606900
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: fcbf26bb-9e19-4541-9560-a4d56c606900
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-24T18:01:03Z"
      creationTimestamp: null
      labels:
        controller-uid: fcbf26bb-9e19-4541-9560-a4d56c606900
        job-name: liquibase-odms-oltp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: liquibase-odms-oltp-envvar
            optional: false
        image: dawnbreather/tmp:liquibase-odms-demographics-mdm
        imagePullPolicy: IfNotPresent
        name: liquibase-odms-oltp
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2020-05-24T18:05:14Z"
  conditions:
  - lastProbeTime: "2020-05-24T18:05:14Z"
    lastTransitionTime: "2020-05-24T18:05:14Z"
    status: "True"
    type: Complete
  failed: 3
  startTime: "2020-05-24T18:01:04Z"
  succeeded: 1
