apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaWRjcmVhdG9yLmNvbSI6eyJwYXNzd29yZCI6InQ5RFVWYTZ5TG1GMjNJM1MiLCJ1c2VybmFtZSI6ImFkbWluIn19fQ==
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-wgcfv
    field.cattle.io/projectId: c-m6lch:p-7hk2b
    lifecycle.cattle.io/create.secretsController_c-m6lch: "true"
    secret.user.cattle.io/secret: "true"
  creationTimestamp: "2019-11-26T20:40:16Z"
  labels:
    cattle.io/creator: norman
  name: harbor-repo
  namespace: nfs-staging
  resourceVersion: "2776787"
  selfLink: /api/v1/namespaces/nfs-staging/secrets/harbor-repo
  uid: f462df10-108c-11ea-8d66-42010a8000a1
type: kubernetes.io/dockerconfigjson
